services:
  app:
    image: ghcr.io/110kanishkamedankara110/fiberops:latest
    container_name: php_app
    restart: always
    ports:
      - "8083:80"
    depends_on:
      - mysql_db
    networks:
      - app-network
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 0724886404Was
      MYSQL_DATABASE: fiberops
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8085:80"
    environment:
      PMA_HOST: mysql_db
      MYSQL_ROOT_PASSWORD: 0724886404Was
    depends_on:
      - mysql_db

volumes:
  db_data:
networks:
  app-network:
    driver: bridge